package com.drizzs.grassworld.update.registries;

import com.drizzs.grassworld.update.blocks.ActualGrass;
import com.drizzs.grassworld.update.blocks.GrassBase;
import com.drizzs.grassworld.update.blocks.UniqueGrassBase;
import com.drizzs.grassworld.update.util.group.GrassGroup;
import com.drizzs.grassworld.update.util.lib.GrassContentLib;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ForgeRegistries;

@Mod.EventBusSubscriber(bus=Mod.EventBusSubscriber.Bus.MOD)
public class GrassBlocks
{
/*
    @SubscribeEvent
    public static void registerBlocks(final RegistryEvent.Register<Block> event)
    {
        //Normal Grass
        GrassContentLib.orange_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState()), "orange_grass");
        GrassContentLib.blue_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState()), "blue_grass");
        GrassContentLib.black_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState()), "black_grass");
        GrassContentLib.white_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState()), "white_grass");
        GrassContentLib.red_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState()), "red_grass");
        GrassContentLib.yellow_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState()), "yellow_grass");
        GrassContentLib.purple_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState()), "purple_grass");
        GrassContentLib.pink_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState()), "pink_grass");
        GrassContentLib.brown_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState()), "brown_grass");
        GrassContentLib.grey_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState()), "grey_grass");
        GrassContentLib.lightgrey_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState()), "lightgrey_grass");
        GrassContentLib.lightblue_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState()), "lightblue_grass");
        GrassContentLib.limegreen_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState()), "limegreen_grass");
        GrassContentLib.green_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState()), "green_grass");
        GrassContentLib.magenta_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState()), "magenta_grass");
        GrassContentLib.cyan_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState()), "cyan_grass");

        //Fancy Grass
        GrassContentLib.fancy_orange_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState()), "fancy_orange_grass");
        GrassContentLib.fancy_blue_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState()), "fancy_blue_grass");
        GrassContentLib.fancy_black_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState()), "fancy_black_grass");
        GrassContentLib.fancy_white_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState()), "fancy_white_grass");
        GrassContentLib.fancy_red_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState()), "fancy_red_grass");
        GrassContentLib.fancy_yellow_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState()), "fancy_yellow_grass");
        GrassContentLib.fancy_purple_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState()), "fancy_purple_grass");
        GrassContentLib.fancy_pink_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState()), "fancy_pink_grass");
        GrassContentLib.fancy_brown_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState()), "fancy_brown_grass");
        GrassContentLib.fancy_grey_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState()), "fancy_grey_grass");
        GrassContentLib.fancy_lightgrey_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState()), "fancy_lightgrey_grass");
        GrassContentLib.fancy_lightblue_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState()), "fancy_lightblue_grass");
        GrassContentLib.fancy_limegreen_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState()), "fancy_limegreen_grass");
        GrassContentLib.fancy_green_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState()), "fancy_green_grass");
        GrassContentLib.fancy_magenta_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState()), "fancy_magenta_grass");
        GrassContentLib.fancy_cyan_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState()), "fancy_cyan_grass");

        //Glowing Grass
        GrassContentLib.glowingorangegrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState()), "glowingorangegrass");
        GrassContentLib.glowingbluegrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState()), "glowingbluegrass");
        GrassContentLib.glowingblackgrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState()), "glowingblackgrass");
        GrassContentLib.glowingwhitegrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState()), "glowingwhitegrass");
        GrassContentLib.glowingredgrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState()), "glowingredgrass");
        GrassContentLib.glowingyellowgrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState()), "glowingyellowgrass");
        GrassContentLib.glowingpurplegrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState()), "glowingpurplegrass");
        GrassContentLib.glowingpinkgrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState()), "glowingpinkgrass");
        GrassContentLib.glowingbrowngrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState()), "glowingbrowngrass");
        GrassContentLib.glowinggreygrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState()), "glowinggreygrass");
        GrassContentLib.glowinglightgreygrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState()), "glowinglightgreygrass");
        GrassContentLib.glowinglightbluegrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState()), "glowinglightbluegrass");
        GrassContentLib.glowinglimegreengrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState()), "glowinglimegreengrass");
        GrassContentLib.glowinggreengrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState()), "glowinggreengrass");
        GrassContentLib.glowingmagentagrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState()), "glowingmagentagrass");
        GrassContentLib.glowingcyangrass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().lightValue(15).hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState()), "glowingcyangrass");

        //Enchanted Grass
        GrassContentLib.enchanted_orange_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState()), "enchanted_orange_grass");
        GrassContentLib.enchanted_blue_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState()), "enchanted_blue_grass");
        GrassContentLib.enchanted_black_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState()), "enchanted_black_grass");
        GrassContentLib.enchanted_white_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState()), "enchanted_white_grass");
        GrassContentLib.enchanted_red_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState()), "enchanted_red_grass");
        GrassContentLib.enchanted_yellow_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState()), "enchanted_yellow_grass");
        GrassContentLib.enchanted_purple_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState()), "enchanted_purple_grass");
        GrassContentLib.enchanted_pink_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState()), "enchanted_pink_grass");
        GrassContentLib.enchanted_brown_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState()), "enchanted_brown_grass");
        GrassContentLib.enchanted_grey_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState()), "enchanted_grey_grass");
        GrassContentLib.enchanted_lightgrey_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState()), "enchanted_lightgrey_grass");
        GrassContentLib.enchanted_lightblue_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState()), "enchanted_lightblue_grass");
        GrassContentLib.enchanted_limegreen_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState()), "enchanted_limegreen_grass");
        GrassContentLib.enchanted_green_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState()), "enchanted_green_grass");
        GrassContentLib.enchanted_magenta_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState()), "enchanted_magenta_grass");
        GrassContentLib.enchanted_cyan_grass = registerBlock(new GrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState()), "enchanted_cyan_grass");

        //Actual Grass
        GrassContentLib.actualgrass_orange = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_orange");
        GrassContentLib.actualgrass_cyan = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_cyan");
        GrassContentLib.actualgrass_red = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_red");
        GrassContentLib.actualgrass_yellow = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_yellow");
        GrassContentLib.actualgrass_brown = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_brown");
        GrassContentLib.actualgrass_pink = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_pink");
        GrassContentLib.actualgrass_purple = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_purple");
        GrassContentLib.actualgrass_green = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_green");
        GrassContentLib.actualgrass_limegreen = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_limegreen");
        GrassContentLib.actualgrass_blue = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_blue");
        GrassContentLib.actualgrass_lightblue = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_lightblue");
        GrassContentLib.actualgrass_grey = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_grey");
        GrassContentLib.actualgrass_lightgrey = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_lightgrey");
        GrassContentLib.actualgrass_magenta = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_magenta");
        GrassContentLib.actualgrass_black = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_black");
        GrassContentLib.actualgrass_white = registerBlock(new ActualGrass((Block.Properties.create(Material.TALL_PLANTS).doesNotBlockMovement().hardnessAndResistance(0).sound(SoundType.PLANT))), "actualgrass_white");

        //Planks
        GrassContentLib.plankblack = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.BLACK).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankblack");
        GrassContentLib.plankred = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.RED).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankred");
        GrassContentLib.plankyellow = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.YELLOW).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankyellow");
        GrassContentLib.plankblue = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankblue");
        GrassContentLib.planklightblue = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "planklightblue");
        GrassContentLib.plankgrey = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.GRAY).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankgrey");
        GrassContentLib.planklightgrey = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "planklightgrey");
        GrassContentLib.plankgreen = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.GREEN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankgreen");
        GrassContentLib.planklimegreen = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.LIME).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "planklimegreen");
        GrassContentLib.plankorange = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.ORANGE_TERRACOTTA).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankorange");
        GrassContentLib.plankpink = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.PINK).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankpink");
        GrassContentLib.plankmagenta = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.MAGENTA).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankmagenta");
        GrassContentLib.plankcyan = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.CYAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankcyan");
        GrassContentLib.plankpurple = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.PURPLE).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankpurple");
        GrassContentLib.plankwhite = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.WHITE_TERRACOTTA).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankwhite");
        GrassContentLib.plankbrown = registerBlock(new Block((Block.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "plankbrown");

        //Normal End Grass
        GrassContentLib.orangeendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState(), Blocks.END_STONE.getDefaultState()), "orangeendgrass");
        GrassContentLib.blueendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState(), Blocks.END_STONE.getDefaultState()), "blueendgrass");
        GrassContentLib.blackendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState(), Blocks.END_STONE.getDefaultState()), "blackendgrass");
        GrassContentLib.whiteendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState(), Blocks.END_STONE.getDefaultState()), "whiteendgrass");
        GrassContentLib.redendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState(), Blocks.END_STONE.getDefaultState()), "redendgrass");
        GrassContentLib.yellowendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState(), Blocks.END_STONE.getDefaultState()), "yellowendgrass");
        GrassContentLib.purpleendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState(), Blocks.END_STONE.getDefaultState()), "purpleendgrass");
        GrassContentLib.pinkendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState(), Blocks.END_STONE.getDefaultState()), "pinkendgrass");
        GrassContentLib.brownendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState(), Blocks.END_STONE.getDefaultState()), "brownendgrass");
        GrassContentLib.greyendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState(), Blocks.END_STONE.getDefaultState()), "greyendgrass");
        GrassContentLib.lightgreyendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState(), Blocks.END_STONE.getDefaultState()), "lightgreyendgrass");
        GrassContentLib.lightblueendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState(), Blocks.END_STONE.getDefaultState()), "lightblueendgrass");
        GrassContentLib.limegreenendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState(), Blocks.END_STONE.getDefaultState()), "limegreenendgrass");
        GrassContentLib.greenendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState(), Blocks.END_STONE.getDefaultState()), "greenendgrass");
        GrassContentLib.magentaendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState(), Blocks.END_STONE.getDefaultState()), "magentaendgrass");
        GrassContentLib.cyanendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState(), Blocks.END_STONE.getDefaultState()), "cyanendgrass");

        //Fancy End Grass
        GrassContentLib.fancyorangeendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancyorangeendgrass");
        GrassContentLib.fancyblueendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancyblueendgrass");
        GrassContentLib.fancyblackendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancyblackendgrass");
        GrassContentLib.fancywhiteendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancywhiteendgrass");
        GrassContentLib.fancyredendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancyredendgrass");
        GrassContentLib.fancyyellowendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancyyellowendgrass");
        GrassContentLib.fancypurpleendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancypurpleendgrass");
        GrassContentLib.fancypinkendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancypinkendgrass");
        GrassContentLib.fancybrownendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancybrownendgrass");
        GrassContentLib.fancygreyendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancygreyendgrass");
        GrassContentLib.fancylightgreyendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancylightgreyendgrass");
        GrassContentLib.fancylightblueendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancylightblueendgrass");
        GrassContentLib.fancylimegreenendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancylimegreenendgrass");
        GrassContentLib.fancygreenendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancygreenendgrass");
        GrassContentLib.fancymagentaendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancymagentaendgrass");
        GrassContentLib.fancycyanendgrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState(), Blocks.END_STONE.getDefaultState()), "fancycyanendgrass");

        //Normal Nether Grass
        GrassContentLib.orangenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "orangenethergrass");
        GrassContentLib.bluenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "bluenethergrass");
        GrassContentLib.blacknethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "blacknethergrass");
        GrassContentLib.whitenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "whitenethergrass");
        GrassContentLib.rednethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "rednethergrass");
        GrassContentLib.yellownethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "yellownethergrass");
        GrassContentLib.purplenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "purplenethergrass");
        GrassContentLib.pinknethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "pinknethergrass");
        GrassContentLib.brownnethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "brownnethergrass");
        GrassContentLib.greynethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "greynethergrass");
        GrassContentLib.lightgreynethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "lightgreynethergrass");
        GrassContentLib.lightbluenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "lightbluenethergrass");
        GrassContentLib.limegreennethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "limegreennethergrass");
        GrassContentLib.greennethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "greennethergrass");
        GrassContentLib.magentanethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "magentanethergrass");
        GrassContentLib.cyannethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "cyannethergrass");

        //Fancy Nether Grass
        GrassContentLib.fancyorangenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_orange.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancyorangenethergrass");
        GrassContentLib.fancybluenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_blue.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancybluenethergrass");
        GrassContentLib.fancyblacknethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_black.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancyblacknethergrass");
        GrassContentLib.fancywhitenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_white.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancywhitenethergrass");
        GrassContentLib.fancyrednethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_red.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancyrednethergrass");
        GrassContentLib.fancyyellownethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_yellow.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancyyellownethergrass");
        GrassContentLib.fancypurplenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_purple.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancypurplenethergrass");
        GrassContentLib.fancypinknethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_pink.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancypinknethergrass");
        GrassContentLib.fancybrownnethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_brown.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancybrownnethergrass");
        GrassContentLib.fancygreynethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_grey.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancygreynethergrass");
        GrassContentLib.fancylightgreynethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightgrey.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancylightgreynethergrass");
        GrassContentLib.fancylightbluenethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_lightblue.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancylightbluenethergrass");
        GrassContentLib.fancylimegreennethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_limegreen.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancylimegreennethergrass");
        GrassContentLib.fancygreennethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_green.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancygreennethergrass");
        GrassContentLib.fancymagentanethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_magenta.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancymagentanethergrass");
        GrassContentLib.fancycyannethergrass = registerBlock(new UniqueGrassBase((Block.Properties.create(Material.ORGANIC).tickRandomly().hardnessAndResistance(0.6F).sound(SoundType.PLANT)), GrassContentLib.actualgrass_cyan.getDefaultState(), Blocks.NETHERRACK.getDefaultState()), "fancycyannethergrass");

        //Logs
        GrassContentLib.black_log = registerBlock(new LogBlock(MaterialColor.BLACK, (Block.Properties.create(Material.WOOD, MaterialColor.BLACK).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "black_log");
        GrassContentLib.red_log = registerBlock(new LogBlock(MaterialColor.RED, (Block.Properties.create(Material.WOOD, MaterialColor.RED).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "red_log");
        GrassContentLib.yellow_log = registerBlock(new LogBlock(MaterialColor.YELLOW, (Block.Properties.create(Material.WOOD, MaterialColor.YELLOW).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "yellow_log");
        GrassContentLib.blue_log = registerBlock(new LogBlock(MaterialColor.BLUE, (Block.Properties.create(Material.WOOD, MaterialColor.BLUE).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "blue_log");
        GrassContentLib.lightblue_log = registerBlock(new LogBlock(MaterialColor.LIGHT_BLUE, (Block.Properties.create(Material.WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "lightblue_log");
        GrassContentLib.grey_log = registerBlock(new LogBlock(MaterialColor.GRAY, (Block.Properties.create(Material.WOOD, MaterialColor.GRAY).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "grey_log");
        GrassContentLib.lightgrey_log = registerBlock(new LogBlock(MaterialColor.LIGHT_GRAY, (Block.Properties.create(Material.WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "lightgrey_log");
        GrassContentLib.green_log = registerBlock(new LogBlock(MaterialColor.GREEN, (Block.Properties.create(Material.WOOD, MaterialColor.GREEN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "green_log");
        GrassContentLib.limegreen_log = registerBlock(new LogBlock(MaterialColor.LIME, (Block.Properties.create(Material.WOOD, MaterialColor.LIME).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "limegreen_log");
        GrassContentLib.orange_log = registerBlock(new LogBlock(MaterialColor.ORANGE_TERRACOTTA, (Block.Properties.create(Material.WOOD, MaterialColor.ORANGE_TERRACOTTA).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "orange_log");
        GrassContentLib.pink_log = registerBlock(new LogBlock(MaterialColor.PINK, (Block.Properties.create(Material.WOOD, MaterialColor.PINK).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "pink_log");
        GrassContentLib.magenta_log = registerBlock(new LogBlock(MaterialColor.MAGENTA, (Block.Properties.create(Material.WOOD, MaterialColor.MAGENTA).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "magenta_log");
        GrassContentLib.cyan_log = registerBlock(new LogBlock(MaterialColor.CYAN, (Block.Properties.create(Material.WOOD, MaterialColor.CYAN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "cyan_log");
        GrassContentLib.purple_log = registerBlock(new LogBlock(MaterialColor.PURPLE, (Block.Properties.create(Material.WOOD, MaterialColor.PURPLE).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "purple_log");
        GrassContentLib.white_log = registerBlock(new LogBlock(MaterialColor.WHITE_TERRACOTTA, (Block.Properties.create(Material.WOOD, MaterialColor.WHITE_TERRACOTTA).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "white_log");
        GrassContentLib.brown_log = registerBlock(new LogBlock(MaterialColor.BROWN, (Block.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD))), "brown_log");

        //Leaves
        GrassContentLib.black_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.BLACK).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "black_leaves");
        GrassContentLib.red_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.RED).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "red_leaves");
        GrassContentLib.yellow_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.YELLOW).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "yellow_leaves");
        GrassContentLib.blue_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.BLUE).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "blue_leaves");
        GrassContentLib.lightblue_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.LIGHT_BLUE).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "lightblue_leaves");
        GrassContentLib.grey_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.GRAY).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "grey_leaves");
        GrassContentLib.lightgrey_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.LIGHT_GRAY).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "lightgrey_leaves");
        GrassContentLib.green_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.GREEN).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "green_leaves");
        GrassContentLib.limegreen_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.LIME).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "limegreen_leaves");
        GrassContentLib.orange_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.ORANGE_TERRACOTTA).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "orange_leaves");
        GrassContentLib.pink_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.PINK).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "pink_leaves");
        GrassContentLib.magenta_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.MAGENTA).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "magenta_leaves");
        GrassContentLib.cyan_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.CYAN).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "cyan_leaves");
        GrassContentLib.purple_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.PURPLE).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "purple_leaves");
        GrassContentLib.white_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.WHITE_TERRACOTTA).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "white_leaves");
        GrassContentLib.brown_leaves = registerBlock(new LeavesBlock((Block.Properties.create(Material.LEAVES, MaterialColor.BROWN).hardnessAndResistance(0).tickRandomly().sound(SoundType.PLANT))), "brown_leaves");

    }

    public static Block registerBlock(Block block, String name) {
        BlockItem itemBlock = new BlockItem(block, new Item.Properties().group(GrassGroup.instance));
        block.setRegistryName(name);
        itemBlock.setRegistryName(name);
        ForgeRegistries.BLOCKS.register(block);
        return block;
    }
    */
}

